---
# For configuration options and examples, please see:
# https://gethomepage.dev/en/configs/services

- My First Group:
    - My First Service:
        href: http://localhost/
        description: Example 1

- My Second Group:
    - My Second Service:
        href: http://localhost/
        description: Example 2

- My Third Group:
    - My Third Service:
        href: http://localhost/
        description: Example 3
